sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      if: branch = master OR tag IS present
      script: ./build_master.sh
    - if: branch != master AND tag IS blank
      script: ./build_branch.sh
