sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - ARCH=armhf
  - ARCH=amd64
  - ARCH=aarch64
  - ARCH=i386

stages:
  - name: test
    if: branch != master AND tag IS blank
  - name: build
    if: branch = master OR tag IS present

jobs:
  include:
    - stage: test
      script: ./build_branch.sh $ARCH
    - name: build
      script: ./build_master.sh $ARCH
