sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - ARCH=armhf
  - ARCH=amd64
  - ARCH=aarch64
  - ARCH=i386

jobs:
  include:
    - stage: build
      if: branch = master OR tag IS present
      script: ./build_master.sh $ARCH
    - if: branch != master AND tag IS blank
      script: ./build_branch.sh $ARCH
