sudo: required

jobs:
  include:
    - stage: lint
      language: nodejs
      cache:
        directories:
          - "node_modules"
      script: npm run lint
    - stage: test
      language: nodejs
      cache:
        directories:
          - "node_modules"
      script: npm run test
    - stage: build
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      env:
        - PLATFORM=armhf
        - PLATFORM=amd64
        - PLATFORM=aarch64
        - PLATFORM=i386
      script: ./build_hassio.sh $PLATFORM
