sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - PLATFORM=armhf
  - PLATFORM=amd64
  - PLATFORM=aarch64
  - PLATFORM=i386

script: ./build_hassio.sh $PLATFORM
