sudo: required

services:
  - docker

script:
  - if [ ! -z "$TRAVIS_TAG" ] || [ "$TRAVIS_BRANCH" == "master" ] ; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    fi

  - if [ ! -z "$TRAVIS_TAG" ] || [ "$TRAVIS_BRANCH" == "master" ] ; then
      docker run \
        --ti \
        --privileged \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v ~/.docker:/root/.docker \
        -v "$PWD":/data \
        homeassistant/build-amd64:latest \
        --all \
        --push
    else
      docker run \
        --privileged \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "$PWD":/docker \
        homeassistant/build-amd64:latest \
        --test
        --all
    fi
