sudo: required

language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: lint
      script: npm run lint
#    - stage: test
#      script: npm run test
    - stage: build
      env: PLATFORM=armhf
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build_hassio.sh $PLATFORM
    - env: PLATFORM=amd64
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build_hassio.sh $PLATFORM
    - env: PLATFORM=amd64
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build_hassio.sh $PLATFORM
    - env: PLATFORM=i386
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build_hassio.sh $PLATFORM
