version: "3.0"
services:
  room-assistant:
    build:
      context: .
      dockerfile: amd64.Dockerfile
    command: run dev
    volumes:
      - .:/app
    environment:
      NAMESPACE:
      LOGGER: 'true'
      LOGLEVEL: info
      SERVICES: mqtt
      MQTT_URL: mqtt://mqtt
  mqtt:
    image: ncarlier/mqtt
