version: "3.0"

services:
  room-assistant:
    build:
      context: .
    env_file: docker-compose.env
    command: run dev
    volumes:
      - .:/app
    environment:
      SERVICES: mqtt
      MQTT_URL: mqtt://mqtt

  mqtt:
    image: ncarlier/mqtt
